---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::upgrade'
    - 'role::upgrade:install'
    - 'role::upgrade:config'

- import_tasks: installation.yml
  tags:
    - 'role::upgrade'
    - 'role::upgrade:install'
