---

dependencies: []

galaxy_info:
  role_name: 'upgrade'
  author: 'Adfinis SyGroup AG'
  description: 'Update and upgrade systems'
  company: 'Adfinis SyGroup AG'
  license: 'GNU General Public License v3'
  min_ansible_version: '2.0.0'
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
        - stretch
    - name: Ubuntu
      versions:
        - focal
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - upgrade
    - distupgrade
